-- Copyright 2016-2018 Gabriel Dubatti. See LICENSE.
toolbar.TTBI_TB = {
  BACKGROUND  = 0,  --toolbar
  NORMAL      = 0,  --button
  SEPARATOR   = 1,  --toolbar
  HILIGHT     = 2,  --button/toolbar
  HIPRESSED   = 3,  --button/toolbar
  TABBACK     = 4,  --tab background
  NTAB1       = 5,  --normal tab1
  NTAB2       = 6,  --normal tab2
  NTAB3       = 7,  --normal tab3
  DTAB1       = 8,  --disabled tab1
  DTAB2       = 9,  --disabled tab2
  DTAB3       = 10, --disabled tab3
  HTAB1       = 11, --highlight tab1
  HTAB2       = 12, --highlight tab2
  HTAB3       = 13, --highlight tab3
  ATAB1       = 14, --active tab1
  ATAB2       = 15, --active tab2
  ATAB3       = 16, --active tab3
  TAB_NSL     = 17, --tab scroll left
  TAB_NSR     = 18, --tab scroll right
  TAB_HSL     = 19, --tab scroll left
  TAB_HSR     = 20, --tab scroll right
  TAB_NCLOSE  = 21, --normal close button
  TAB_HCLOSE  = 22, --highlight close button
  TAB_CHANGED = 23, --changed indicator
  TXT_HIL1    = 24, --highlight text button1
  TXT_HIL2    = 25, --highlight text button2
  TXT_HIL3    = 26, --highlight text button3
  TXT_HPR1    = 27, --hi-pressed text button1
  TXT_HPR2    = 28, --hi-pressed text button2
  TXT_HPR3    = 29, --hi-pressed text button3
  HINORMAL    = 30, --normal button back
  TXT_NOR1    = 31, --normal text button1 back
  TXT_NOR2    = 32, --normal text button2 back
  TXT_NOR3    = 33, --normal text button3 back
  TXT_NOR4    = 34, --replace TTBI_TB_TXT_NOR3 (add a drop down button at the end)
  TXT_HIL4    = 35, --replace TTBI_TB_TXT_HIL3 (add a drop down button at the end)
  TXT_HPR4    = 36, --replace TTBI_TB_TXT_HPR3 (add a drop down button at the end)
  N           = 37
}
